export default [
    {
        name: "建材",
        lore: "<<Click>>",
        icon: "minecraft:oak_log",
        items: [
            { id: "minecraft:oak_log", price: 10 },
            { id: "minecraft:acacia_log", price: 10 },
            { id: "minecraft:birch_log", price: 10 },
            { id: "minecraft:dark_oak_log", price: 10 },
            { id: "minecraft:jungle_log", price: 10 },
            { id: "minecraft:mangrove_log", price: 10 },
            { id: "minecraft:spruce_log", price: 10 },
            { id: "minecraft:warped_stem", price: 10 },
            { id: "minecraft:crimson_stem", price: 10 },
            { id: "minecraft:oak_planks", price: 10 },
            { id: "minecraft:acacia_planks", price: 10 },
            { id: "minecraft:birch_planks", price: 10 },
            { id: "minecraft:dark_oak_planks", price: 10 },
            { id: "minecraft:jungle_planks", price: 10 },
            { id: "minecraft:mangrove_planks", price: 10 },
            { id: "minecraft:spruce_planks", price: 10 },
            { id: "minecraft:warped_planks", price: 10 },
            { id: "minecraft:crimson_planks", price: 10 },
            { id: "minecraft:cobblestone", price: 10 },
            { id: "minecraft:andesite", price: 10 },
            { id: "minecraft:diorite", price: 10 },
            { id: "minecraft:granite", price: 10 },
            { id: "minecraft:deepslate", price: 10 },
            { id: "minecraft:cobblestone_wall", price: 10 },
            { id: "minecraft:andesite_wall", price: 10 },
            { id: "minecraft:diorite_wall", price: 10 },
            { id: "minecraft:granite_wall", price: 10 },
            { id: "minecraft:deepslate_wall", price: 10 },
            { id: "minecraft:cobblestone_stairs", price: 10 },
            { id: "minecraft:andesite_stairs", price: 10 },
            { id: "minecraft:diorite_stairs", price: 10 },
            { id: "minecraft:granite_stairs", price: 10 },
            { id: "minecraft:deepslate_stairs", price: 10 },
            { id: "minecraft:cobblestone_slab", price: 10 },
            { id: "minecraft:andesite_slab", price: 10 },
            { id: "minecraft:diorite_slab", price: 10 },
            { id: "minecraft:granite_slab", price: 10 },
            { id: "minecraft:deepslate_slab", price: 10 },
        ]
    }
]