export default [
    {
        name: `cw.shop.building`,
        lore: `<<Click here>>`,
        icon: `minecraft:oak_log`,
        items: [
            { id: `minecraft:oak_log`, price: 15 },
            { id: `minecraft:acacia_log`, price: 15 },
            { id: `minecraft:birch_log`, price: 15 },
            { id: `minecraft:cherry_log`, price: 15 },
            { id: `minecraft:dark_oak_log`, price: 15 },
            { id: `minecraft:jungle_log`, price: 15 },
            { id: `minecraft:mangrove_log`, price: 15 },
            { id: `minecraft:spruce_log`, price: 15 },
            { id: `minecraft:pale_oak_log`, price: 15 },
            { id: `minecraft:gravel`, price: 10 },
            { id: `minecraft:white_concrete`, price: 20 },
            { id: `minecraft:white_concrete_powder`, price: 15 },
            { id: `minecraft:glass`, price: 20 },
            { id: `minecraft:quartz_block`, price: 30 },
            { id: `minecraft:sandstone`, price: 20 },
            { id: `minecraft:brick_block`, price: 25 },
            { id: `minecraft:stonebrick`, price: 25 },
            { id: `minecraft:cobblestone`, price: 10 },
            { id: `minecraft:cobbled_deepslate`, price: 25 },
            { id: `minecraft:white_wool`, price: 20 },
            { id: `minecraft:hardened_clay`, price: 20 },
            { id: `minecraft:white_terracotta`, price: 30 },
            { id: `minecraft:calcite`, price: 35 },
            { id: `minecraft:prismarine_bricks`, price: 50 },
            { id: `minecraft:brick`, price: 10 },
            { id: `minecraft:netherbrick`, price: 40 },
        ]
    },
    {
        name: `cw.shop.food`,
        lore: `<<Click here>>`,
        icon: `minecraft:bread`,
        items: [
            { id: `minecraft:bread`, price: 100 },
            { id: `minecraft:cooked_chicken`, price: 120 },
            { id: `minecraft:cooked_porkchop`, price: 120 },
            { id: `minecraft:cooked_mutton`, price: 120 },
            { id: `minecraft:cooked_beef`, price: 150 },
            { id: `minecraft:cooked_rabbit`, price: 120 },
            { id: `minecraft:cooked_salmon`, price: 140 },
            { id: `minecraft:cooked_cod`, price: 140 },
        ]
    },
    {
        name: `cw.shop.mob_drop`,
        lore: `<<Click here>>`,
        icon: `minecraft:bone`,
        items: [
            { id: `minecraft:blaze_rod`, price: 200 },
            { id: `minecraft:magma_cream`, price: 180 },
            { id: `minecraft:shulker_shell`, price: 350 },
            { id: `minecraft:rotten_flesh`, price: 80 },
            { id: `minecraft:spider_eye`, price: 150 },
            { id: `minecraft:gunpowder`, price: 200 },
        ]
    },
    {
        name: `cw.shop.farm`,
        lore: `<<Click here>>`,
        icon: `minecraft:carrot`,
        items: [
            { id: `minecraft:apple`, price: 150 },
            { id: `minecraft:potato`, price: 50 },
            { id: `minecraft:carrot`, price: 50 },
            { id: `minecraft:beetroot_seeds`, price: 40 },
            { id: `minecraft:pumpkin_seeds`, price: 40 },
            { id: `minecraft:melon_seeds`, price: 40 },
            { id: `minecraft:cherry_sapling`, price: 120 },
            { id: `minecraft:acacia_sapling`, price: 120 },
            { id: `minecraft:birch_sapling`, price: 120 },
            { id: `minecraft:dark_oak_sapling`, price: 120 },
            { id: `minecraft:jungle_sapling`, price: 120 },
            { id: `minecraft:oak_sapling`, price: 100 },
            { id: `minecraft:pale_oak_sapling`, price: 120 },
            { id: `minecraft:spruce_sapling`, price: 120 },
            { id: `minecraft:dandelion`, price: 30 },
            { id: `minecraft:poppy`, price: 30 },
            { id: `minecraft:blue_orchid`, price: 30 },
            { id: `minecraft:allium`, price: 30 },
            { id: `minecraft:azure_bluet`, price: 30 },
            { id: `minecraft:red_tulip`, price: 30 },
            { id: `minecraft:orange_tulip`, price: 30 },
            { id: `minecraft:white_tulip`, price: 30 },
            { id: `minecraft:pink_tulip`, price: 30 },
            { id: `minecraft:oxeye_daisy`, price: 30 },
            { id: `minecraft:cornflower`, price: 30 },
            { id: `minecraft:lily_of_the_valley`, price: 30 },
            { id: `minecraft:sunflower`, price: 40 },
            { id: `minecraft:lilac`, price: 40 },
            { id: `minecraft:rose_bush`, price: 40 },
            { id: `minecraft:peony`, price: 40 },
            { id: `minecraft:pink_petals`, price: 40 },
        ]
    },
    {
        name: `cw.shop.other1`,
        lore: `<<Click here>>`,
        icon: `minecraft:netherrack`,
        items: [
            { id: `minecraft:quartz`, price: 5 },
            { id: `minecraft:warped_fungus`, price: 80 },
            { id: `minecraft:crimson_fungus`, price: 80 },
            { id: `minecraft:soul_soil`, price: 30 },
            { id: `minecraft:soul_sand`, price: 30 },
            { id: `minecraft:warped_nylium`, price: 40 },
            { id: `minecraft:crimson_nylium`, price: 40 },
            { id: `minecraft:netherrack`, price: 20 },
            { id: `minecraft:blackstone`, price: 25 },
            { id: `minecraft:basalt`, price: 50 },
            { id: `minecraft:ancient_debris`, price: 15000 },
            { id: `minecraft:sponge`, price: 500 },
            { id: `minecraft:glowstone`, price: 100 },
            { id: `minecraft:purpur_block`, price: 60 },
            { id: `minecraft:end_stone`, price: 30 },
            { id: `minecraft:crimson_stem`, price: 70 },
            { id: `minecraft:warped_stem`, price: 70 },
            { id: `minecraft:sculk`, price: 100 },
            { id: `minecraft:sculk_catalyst`, price: 120 },
            { id: `minecraft:mycelium`, price: 50 },
        ]
    },
    {
        name: `cw.shop.other2`,
        lore: `<<Click here>>`,
        icon: `minecraft:torch`,
        items: [
            { id: `minecraft:torch`, price: 20 },
            { id: `minecraft:lantern`, price: 50 },
            { id: `minecraft:nether_wart`, price: 250 },
            { id: `minecraft:lead`, price: 150 },
            { id: `minecraft:name_tag`, price: 400 },
            { id: `minecraft:end_rod`, price: 60 },
            { id: `minecraft:blue_ice`, price: 40 },
            { id: `minecraft:music_disc_pigstep`, price: 5000 },
            { id: `minecraft:experience_bottle`, price: 300 },
            { id: `minecraft:heart_of_the_sea`, price: 5000 },
            { id: `minecraft:mace`, price: 80000 },
            { id: `minecraft:elytra`, price: 100000 },
        ]
    },
    {
        name: `cw.shop.original`,
        lore: `<<Click here>>`,
        icon: `cw:toyphone`,
        items: [
            { id: `cw:toyphone`, price: 0 },
            { id: `cw:toyphone_blue`, price: 50 },
            { id: `cw:toyphone_red`, price: 50 },
            { id: `cw:toyphone_white`, price: 50 },

        ]
    }
];
