export class Data {
    static wordOrder = [
        "A", "B", "C", "D", "E", "F", "G",
        "H", "I", "J", "K", "L", "M", "N",
        "O", "P", "Q", "R", "S", "T", "U",
        "V", "W", "X", "Y", "Z",
        "a", "b", "c", "d", "e", "f", "g",
        "h", "i", "j", "k", "l", "m", "n",
        "o", "p", "q", "r", "s", "t", "u",
        "v", "w", "x", "y", "z",
        "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"
    ]
    static permissions =
        [
            "information",
            "permission",
            "member_invite",
            "member_kick",
            "money_deposit",
            "money_withdraw",
            "diplomacy"
        ]
    static enchantsLang = {
        "power": "enchantment.arrowDamage",
        "flame": "enchantment.arrowFire",
        "infinity": "enchantment.arrowInfinite",
        "punch": "enchantment.arrowKnockback",
        "multishot": "enchantment.crossbowMultishot",
        "piercing": "enchantment.crossbowPiercing",
        "quick_charge": "enchantment.crossbowQuickCharge",
        "binding_curse": "enchantment.curse.binding",
        "vanishing_curse": "enchantment.curse.vanishing",
        "sharpness": "enchantment.damage.all",
        "bane_of_arthropods": "enchantment.damage.arthropods",
        "smite": "enchantment.damage.undead",
        "efficiency": "enchantment.digging",
        "unbreaking": "enchantment.durability",
        "fire_aspect": "enchantment.fire",
        "lure": "enchantment.fishingSpeed",
        "frost_walker": "enchantment.frostwalker",
        "breach": "enchantment.heavy_weapon.breach",
        "density": "enchantment.heavy_weapon.density",
        "wind_burst": "enchantment.heavy_weapon.windburst",
        "knockback": "enchantment.knockback",
        "looting": "enchantment.lootBonus",
        "fortune": "enchantment.lootBonusDigger",
        "luck_of_the_sea": "enchantment.lootBonusFishing",
        "mending": "enchantment.mending",
        "respiration": "enchantment.oxygen",
        "protection": "enchantment.protect.all",
        "blast_protection": "enchantment.protect.explosion",
        "feather_falling": "enchantment.protect.fall",
        "fire_protection": "enchantment.protect.fire",
        "projectile_protection": "enchantment.protect.projectile",
        "soul_speed": "enchantment.soul_speed",
        "swift_sneak": "enchantment.swift_sneak",
        "thorns": "enchantment.thorns",
        "silk_touch": "enchantment.untouching",
        "depth_strider": "enchantment.waterWalker",
        "aqua_affinity": "enchantment.waterWorker",
        "channeling": "enchantment.tridentChanneling",
        "loyalty": "enchantment.tridentLoyalty",
        "riptide": "enchantment.tridentRiptide",
        "impaling": "enchantment.tridentImpaling"
    }
    static usableBlocks = [
        "minecraft:chest",
        "minecraft:trapped_chest",
        "minecraft:barrel",
        "minecraft:shulker_box",
        "minecraft:white_shulker_box",
        "minecraft:orange_shulker_box",
        "minecraft:magenta_shulker_box",
        "minecraft:light_blue_shulker_box",
        "minecraft:yellow_shulker_box",
        "minecraft:lime_shulker_box",
        "minecraft:pink_shulker_box",
        "minecraft:gray_shulker_box",
        "minecraft:light_gray_shulker_box",
        "minecraft:cyan_shulker_box",
        "minecraft:purple_shulker_box",
        "minecraft:blue_shulker_box",
        "minecraft:brown_shulker_box",
        "minecraft:green_shulker_box",
        "minecraft:red_shulker_box",
        "minecraft:black_shulker_box",
        "minecraft:crafting_table",
        "minecraft:furnace",
        "minecraft:blast_furnace",
        "minecraft:smoker",
        "minecraft:anvil",
        "minecraft:chipped_anvil",
        "minecraft:damaged_anvil",
        "minecraft:grindstone",
        "minecraft:cartography_table",
        "minecraft:loom",
        "minecraft:stonecutter",
        "minecraft:enchanting_table",
        "minecraft:brewing_stand",
        "minecraft:lever",
        "minecraft:wooden_button",
        "minecraft:stone_button",
        "minecraft:acacia_button",
        "minecraft:birch_button",
        "minecraft:dark_oak_button",
        "minecraft:jungle_button",
        "minecraft:spruce_button",
        "minecraft:crimson_button",
        "minecraft:warped_button",
        "minecraft:polished_blackstone_button",
        "minecraft:acacia_pressure_plate",
        "minecraft:birch_pressure_plate",
        "minecraft:dark_oak_pressure_plate",
        "minecraft:jungle_pressure_plate",
        "minecraft:spruce_pressure_plate",
        "minecraft:stone_pressure_plate",
        "minecraft:wooden_pressure_plate",
        "minecraft:heavy_weighted_pressure_plate",
        "minecraft:light_weighted_pressure_plate",
        "minecraft:crimson_pressure_plate",
        "minecraft:warped_pressure_plate",
        "minecraft:polished_blackstone_pressure_plate",
        "minecraft:noteblock",
        "minecraft:repeater",
        "minecraft:comparator",
        "minecraft:tripwire_hook",
        "minecraft:daylight_detector",
        "minecraft:oak_door",
        "minecraft:spruce_door",
        "minecraft:birch_door",
        "minecraft:jungle_door",
        "minecraft:acacia_door",
        "minecraft:dark_oak_door",
        "minecraft:iron_door",
        "minecraft:crimson_door",
        "minecraft:warped_door",
        "minecraft:oak_trapdoor",
        "minecraft:spruce_trapdoor",
        "minecraft:birch_trapdoor",
        "minecraft:jungle_trapdoor",
        "minecraft:acacia_trapdoor",
        "minecraft:dark_oak_trapdoor",
        "minecraft:iron_trapdoor",
        "minecraft:crimson_trapdoor",
        "minecraft:warped_trapdoor",
        "minecraft:oak_fence_gate",
        "minecraft:spruce_fence_gate",
        "minecraft:birch_fence_gate",
        "minecraft:jungle_fence_gate",
        "minecraft:acacia_fence_gate",
        "minecraft:dark_oak_fence_gate",
        "minecraft:crimson_fence_gate",
        "minecraft:warped_fence_gate",
        "minecraft:bed",
        "minecraft:bell",
        "minecraft:composter",
        "minecraft:jukebox",
        "minecraft:lectern",
        "minecraft:respawn_anchor",
        "minecraft:beacon",
        "minecraft:conduit",
        "minecraft:dispenser",
        "minecraft:dropper",
        "minecraft:hopper",
        "minecraft:cauldron",
        "minecraft:ender_chest",
        "minecraft:crafter",
        "minecraft:vault",
        "minecraft:trial_spawner",
        "minecraft:copper_bulb",
        "minecraft:beehive",
        "minecraft:bee_nest",
        "minecraft:sweet_berry_bush",
        "minecraft:cave_vines",
        "minecraft:cave_vines_body_with_berries",
        "minecraft:cave_vines_head_with_berries",
        "minecraft:suspicious_sand",
        "minecraft:suspicious_gravel",
        "minecraft:cherry_leaves",
        "minecraft:chiseled_bookshelf",
        "minecraft:decorated_pot",
        "minecraft:pink_petals",
        "minecraft:big_dripleaf"
    ]
}